"^wasm(32|64)-": {
    switches ~= [
        "-defaultlib=",
        "-L-z",
        "-Lstack-size=1048576",
        "-L--stack-first",
        "-link-internally",
        "-L--export-dynamic",
    ];
    lib-dirs = [];
};
"default": {
    lib-dirs = [];
    rpath = "";
    post-switches ~= [
        "-I=%%ldcbinarypath%%/../import/ldc",
        "--mv=ldc=./"
    ];
};
