"^wasm(32|64)-": {
    switches ~= [
        "-defaultlib=",
        "-L-z",
        "-Lstack-size=1048576",
        "-L--stack-first",
        "-link-internally",
        "-L--export-dynamic",
    ];
    lib-dirs = [];
};
"default": {
    lib-dirs = [];
    rpath = "";
    post-switches ~= [
        "-I=%%ldcbinarypath%%/../",
        "--mv=ldc=import/ldc/",
        "--mv=core.stdc=import/core/stdc",
        "--mv=core.sys=import/core/sys"
    ];
};
