"^wasm(32|64)-.*wasip2": {
    switches ~= [
        "-defaultlib=",
        "-L-z",
        "-Lstack-size=1048576",
        "--static",
        "-L--stack-first",
        "-L--export-dynamic",
    ];
    lib-dirs = ["%%ldcbinarypath%%/../lib-wasi"];
    post-switches = [
        "-I=%%ldcbinarypath%%/../import-wasm/",
        "--gcc=wasm32-wasip2-clang",
        "--Xcc=--sysroot=%%ldcbinarypath%%/../../wasi-sdk/share/wasi-sysroot",
        "--linker=wasm-ld",
    ];
};
