"^wasm32-.*-wasip2": {
    switches ~= [
        "-defaultlib=",
        "-L-z",
        "-Lstack-size=1048576",
        "--static",
        "-L--stack-first",
        "-L--export-dynamic",
        "-L--allow-multiple-definition"
    ];
    lib-dirs = [
        "%%ldcbinarypath%%/../../../wasi-sdk/share/wasi-sysroot/lib/wasm32-wasip2/",
        "%%ldcbinarypath%%/../../../wasi-sdk/share/wasi-sysroot/lib/wasm32-wasip2/eh/",
        "%%ldcbinarypath%%/../../../wasi-sdk/lib/clang/22/lib/wasm32-unknown-wasip2/",
        "%%ldcbinarypath%%/../../../wasi-sdk/lib/"
    ];
    post-switches = [
        "-I%%ldcbinarypath%%/../import-wasm/",
        "--gcc=wasm32-wasip2-clang",
        "--Xcc=--sysroot=%%ldcbinarypath%%/../../../wasi-sdk/share/wasi-sysroot",
        "--linker=wasm-ld",
        "-L-lc",
        "-L-lm",
        "-L-lc++",
        "-L-lc++abi",
        "-L-lunwind",
        "-L-lz",
        "-L-lclang_rt.builtins"
    ];
};
"^wasm32-.*-wasi": {
    switches ~= [
        "-defaultlib=",
        "-L-z",
        "-Lstack-size=1048576",
        "--static",
        "-L--stack-first",
        "-L--export-dynamic",
        "-L--allow-multiple-definition"
    ];
    lib-dirs = [
        "%%ldcbinarypath%%/../../../wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi/",
        "%%ldcbinarypath%%/../../../wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi/eh/",
        "%%ldcbinarypath%%/../../../wasi-sdk/lib/clang/22/lib/wasm32-unknown-wasi/",
        "%%ldcbinarypath%%/../../../wasi-sdk/lib/"
    ];
    post-switches = [
        "-I%%ldcbinarypath%%/../import-wasm/",
        "--gcc=wasm32-wasi-clang",
        "--Xcc=--sysroot=%%ldcbinarypath%%/../../../wasi-sdk/share/wasi-sysroot",
        "--linker=wasm-ld",
        "-L-lc",
        "-L-lm",
        "-L-lc++",
        "-L-lc++abi",
        "-L-lunwind",
        "-L-lz",
        "-L-lclang_rt.builtins"
    ];
};
